name: Email Action Test

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: 24f2004230@ds.study.iitm.ac.in
      run: echo "Hello from IITM email step!"
      
    - name: Regular step
      run: echo "Workflow completed successfully"
